/*
 * Where each character's eyes are on their sprite, as fractions of the picture, so
 * assets/sprites/<id>/blink.png (half closed above, closed below) can be laid over
 * them for a blink. Generated by tools/paint-blinks.js.
 */
window.VN_BLINKS = {
  "helene": {"x":0.40367,"y":0.21059,"w":0.23853,"h":0.04235},
  "herve": {"x":0.38793,"y":0.25765,"w":0.31034,"h":0.03882},
  "balbadiou": {"x":0.3555,"y":0.24235,"w":0.27982,"h":0.04353},
  "harakei": {"x":0.3391,"y":0.27059,"w":0.35986,"h":0.03647},
  "woman": {"x":0.4147,"y":0.30824,"w":0.27034,"h":0.04353},
  "blanche": {"x":0.38623,"y":0.27294,"w":0.16444,"h":0.02941}
};
