/*
 * Where each character's eyes are on their sprite, as fractions of the picture, so
 * assets/sprites/<id>/blink.png (half closed above, closed below) can be laid over
 * them for a blink. Generated by tools/paint-blinks.js.
 */
window.VN_BLINKS = {
  "helene": {"x":0.41284,"y":0.21176,"w":0.22477,"h":0.03882},
  "herve": {"x":0.39198,"y":0.25647,"w":0.33333,"h":0.03882},
  "balbadiou": {"x":0.35469,"y":0.24118,"w":0.27918,"h":0.04353},
  "harakei": {"x":0.33793,"y":0.26941,"w":0.35862,"h":0.03647},
  "woman": {"x":0.4147,"y":0.30824,"w":0.27034,"h":0.04353},
  "blanche": {"x":0.3855,"y":0.27176,"w":0.16412,"h":0.02941},
  "herve_army": {"x":0.36789,"y":0.25647,"w":0.3612,"h":0.03882}
};
