/*
 * Each character's expressions (assets/sprites/<id>/<expression>.webp), which of them can
 * blink with the painted eyelids, and where the face is on the sprite (a square, as fractions
 * of the sprite's width and height) for the portrait in the text box.
 * Generated by tools/import-sprites.js.
 */
window.VN_EXPRESSIONS = {
  "balbadiou": {"expressions":["angry","neutral","serious","surprised","uneasy","worried"],"blink":["neutral"],"face":{"x":0.09611,"y":0.09882,"s":0.70481},"eyes":[{"a":[160,222],"b":[212,221],"up":[185,210.5],"low":[185,236.5]},{"a":[272,222],"b":[240.5,221],"up":[257,211.2],"low":[258,235]}]},
  "blanche": {"expressions":["grave","neutral","smile","soft","surprised"],"blink":["neutral"],"face":{"x":0.16221,"y":0.17529,"s":0.53626},"eyes":[{"a":[207,237],"b":[235,249.5],"up":[220,236],"low":[222,250.5],"flick":true},{"a":[283,237.5],"b":[262,248.5],"up":[273,236],"low":[273,250]}]},
  "harakei": {"expressions":["amused","angry","furious","neutral","speaking","stern"],"blink":["neutral","stern"],"face":{"x":-0.04138,"y":0.12941,"s":1.02414},"eyes":[{"a":[103.5,236],"b":[148.5,251],"up":[125,234.5],"low":[130,254]},{"a":[197,240],"b":[172,251.5],"up":[185,237.5],"low":[185,254.5]}]},
  "helene": {"expressions":["neutral","sad","surprised","upset"],"blink":["neutral"],"face":{"x":0.1422,"y":0.06118,"s":0.73853},"eyes":[{"a":[185.5,198.5],"b":[224.5,204.5],"up":[205,187.2],"low":[206,208]},{"a":[273,187.5],"b":[250,202.5],"up":[261,185.2],"low":[261,204]}]},
  "herve": {"expressions":["angry","happy","neutral","sad","surprised","uneasy"],"blink":["neutral"],"face":{"x":0,"y":0.03176,"s":1.0216},"eyes":[{"a":[132,223.5],"b":[173,241],"up":[152,226],"low":[157,244]},{"a":[230,229],"b":[200,240.5],"up":[214,227.5],"low":[214,245.5]}]},
  "herve_army": {"expressions":["neutral"],"blink":["neutral"],"face":{"x":-0.01338,"y":0.07059,"s":1.00334},"eyes":[{"a":[115,223.5],"b":[156,241],"up":[135,226],"low":[140,244]},{"a":[213,229],"b":[183,240.5],"up":[197,227.5],"low":[197,245.5]}]},
  "woman": {"expressions":["cold","neutral","sad","smile","surprised","worried"],"blink":["neutral"],"face":{"x":0.12598,"y":0.19412,"s":0.72178},"eyes":[{"a":[163,267],"b":[202,283],"up":[183,268.4],"low":[185,293.5],"flick":true},{"a":[256,267],"b":[224.5,281],"up":[240,268.4],"low":[240,293.5],"flick":true}]}
};
