/* Generated by tools/paint-backgrounds.js: how each painted background's layers stack and move. */
window.VN_SCENERY = {
 "army_camp": {
  "flat": "assets/scenes/army_camp/flat.png",
  "vignette": [
   0.3,
   "40,20,40"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/army_camp/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 6,
    "w": 480,
    "h": 92,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 260
    },
    "src": "assets/scenes/army_camp/clouds.png"
   },
   {
    "id": "giants",
    "x": 15,
    "y": 66,
    "w": 465,
    "h": 103,
    "depth": 0.07,
    "anim": null,
    "src": "assets/scenes/army_camp/giants.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 118,
    "w": 480,
    "h": 63,
    "depth": 0.1,
    "anim": null,
    "src": "assets/scenes/army_camp/far.png"
   },
   {
    "id": "walls",
    "x": 0,
    "y": 139,
    "w": 480,
    "h": 45,
    "depth": 0.22,
    "anim": null,
    "src": "assets/scenes/army_camp/walls.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 164,
    "w": 480,
    "h": 106,
    "depth": 0.3,
    "anim": null,
    "src": "assets/scenes/army_camp/land.png"
   },
   {
    "id": "hq",
    "x": 54,
    "y": 86,
    "w": 253,
    "h": 106,
    "depth": 0.32,
    "anim": null,
    "src": "assets/scenes/army_camp/hq.png"
   },
   {
    "id": "flagHQ",
    "x": 121,
    "y": 87,
    "w": 13,
    "h": 8,
    "depth": 0.32,
    "anim": {
     "type": "sway",
     "a": 3,
     "t": 1.8,
     "ox": 0,
     "oy": 0
    },
    "src": "assets/scenes/army_camp/flagHQ.png"
   },
   {
    "id": "tents",
    "x": 3,
    "y": 181,
    "w": 477,
    "h": 61,
    "depth": 0.4,
    "anim": null,
    "src": "assets/scenes/army_camp/tents.png"
   },
   {
    "id": "camp",
    "x": 9,
    "y": 115,
    "w": 442,
    "h": 141,
    "depth": 0.5,
    "anim": null,
    "src": "assets/scenes/army_camp/camp.png"
   },
   {
    "id": "flag10",
    "x": 12,
    "y": 119,
    "w": 26,
    "h": 14,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 3,
     "t": 2,
     "ox": 0,
     "oy": 0
    },
    "src": "assets/scenes/army_camp/flag10.png"
   },
   {
    "id": "banner356",
    "x": 348,
    "y": 184,
    "w": 18,
    "h": 29,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 1.5,
     "t": 2.6,
     "ox": 0,
     "oy": 0
    },
    "src": "assets/scenes/army_camp/banner356.png"
   },
   {
    "id": "grass",
    "x": 3,
    "y": 246,
    "w": 476,
    "h": 24,
    "depth": 0.6,
    "anim": {
     "type": "sway",
     "a": 4,
     "t": 3.2
    },
    "src": "assets/scenes/army_camp/grass.png"
   }
  ]
 },
 "aviary": {
  "flat": "assets/scenes/aviary/flat.png",
  "vignette": [
   0.32,
   "20,20,10"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/aviary/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 22,
    "w": 480,
    "h": 74,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 240
    },
    "src": "assets/scenes/aviary/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 101,
    "w": 480,
    "h": 63,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/aviary/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 22,
    "w": 480,
    "h": 248,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/aviary/land.png"
   },
   {
    "id": "maple0",
    "x": 373,
    "y": 82,
    "w": 107,
    "h": 114,
    "depth": 0.4,
    "anim": {
     "type": "sway",
     "a": 1,
     "t": 6.627779726870358
    },
    "src": "assets/scenes/aviary/maple0.png"
   },
   {
    "id": "maple1",
    "x": 0,
    "y": 173,
    "w": 78,
    "h": 77,
    "depth": 0.4,
    "anim": {
     "type": "sway",
     "a": 1,
     "t": 5.526072917506099
    },
    "src": "assets/scenes/aviary/maple1.png"
   },
   {
    "id": "grass",
    "x": 1,
    "y": 238,
    "w": 467,
    "h": 32,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 5,
     "t": 3.4
    },
    "src": "assets/scenes/aviary/grass.png"
   }
  ]
 },
 "balbadiou_office": {
  "flat": "assets/scenes/balbadiou_office/flat.png",
  "vignette": [
   0.45,
   "20,10,0"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/balbadiou_office/sky.png"
   },
   {
    "id": "pendulum",
    "x": 310,
    "y": 90,
    "w": 6,
    "h": 39,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 9,
     "t": 2,
     "oy": 0
    },
    "src": "assets/scenes/balbadiou_office/pendulum.png"
   }
  ]
 },
 "blanche_salon": {
  "flat": "assets/scenes/blanche_salon/flat.png",
  "vignette": [
   0.55,
   "20,4,6"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/blanche_salon/sky.png"
   },
   {
    "id": "drape",
    "x": 455,
    "y": 33,
    "w": 14,
    "h": 157,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 1,
     "t": 7,
     "oy": 0
    },
    "src": "assets/scenes/blanche_salon/drape.png"
   },
   {
    "id": "palm",
    "x": 413,
    "y": 191,
    "w": 46,
    "h": 40,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 2.5,
     "t": 5
    },
    "src": "assets/scenes/blanche_salon/palm.png"
   }
  ]
 },
 "burned_village": {
  "flat": "assets/scenes/burned_village/flat.png",
  "vignette": [
   0.55,
   "10,0,0"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/burned_village/sky.png"
   },
   {
    "id": "smokeclouds",
    "x": 0,
    "y": 19,
    "w": 480,
    "h": 84,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 80
    },
    "src": "assets/scenes/burned_village/smokeclouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 128,
    "w": 480,
    "h": 33,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/burned_village/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 61,
    "w": 480,
    "h": 209,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/burned_village/land.png"
   }
  ]
 },
 "cemetery": {
  "flat": "assets/scenes/cemetery/flat.png",
  "vignette": [
   0.4,
   "30,10,20"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/cemetery/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 29,
    "w": 480,
    "h": 80,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 230
    },
    "src": "assets/scenes/cemetery/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 68,
    "w": 480,
    "h": 107,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/cemetery/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 158,
    "w": 480,
    "h": 112,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/cemetery/land.png"
   },
   {
    "id": "cypress0",
    "x": 7,
    "y": 60,
    "w": 30,
    "h": 132,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 8.526817149482667
    },
    "src": "assets/scenes/cemetery/cypress0.png"
   },
   {
    "id": "cypress1",
    "x": 33,
    "y": 92,
    "w": 22,
    "h": 96,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 6.575923861004412
    },
    "src": "assets/scenes/cemetery/cypress1.png"
   },
   {
    "id": "cypress2",
    "x": 436,
    "y": 54,
    "w": 32,
    "h": 140,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 8.078905261354521
    },
    "src": "assets/scenes/cemetery/cypress2.png"
   },
   {
    "id": "cypress3",
    "x": 416,
    "y": 98,
    "w": 20,
    "h": 90,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 6.106843292014673
    },
    "src": "assets/scenes/cemetery/cypress3.png"
   },
   {
    "id": "plane",
    "x": 358,
    "y": 46,
    "w": 122,
    "h": 204,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.7,
     "t": 8,
     "ox": 0.7
    },
    "src": "assets/scenes/cemetery/plane.png"
   },
   {
    "id": "grass",
    "x": 2,
    "y": 237,
    "w": 476,
    "h": 32,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 5,
     "t": 3.6
    },
    "src": "assets/scenes/cemetery/grass.png"
   }
  ]
 },
 "cemetery_grey": {
  "flat": "assets/scenes/cemetery_grey/flat.png",
  "vignette": [
   0.45,
   "20,22,30"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/cemetery_grey/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 3,
    "w": 480,
    "h": 106,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 120
    },
    "src": "assets/scenes/cemetery_grey/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 68,
    "w": 480,
    "h": 107,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/cemetery_grey/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 158,
    "w": 480,
    "h": 112,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/cemetery_grey/land.png"
   },
   {
    "id": "cypress0",
    "x": 7,
    "y": 60,
    "w": 30,
    "h": 132,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 8.08023109473288
    },
    "src": "assets/scenes/cemetery_grey/cypress0.png"
   },
   {
    "id": "cypress1",
    "x": 33,
    "y": 92,
    "w": 22,
    "h": 96,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 7.527799895731732
    },
    "src": "assets/scenes/cemetery_grey/cypress1.png"
   },
   {
    "id": "cypress2",
    "x": 436,
    "y": 54,
    "w": 32,
    "h": 140,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 8.534485202981159
    },
    "src": "assets/scenes/cemetery_grey/cypress2.png"
   },
   {
    "id": "cypress3",
    "x": 416,
    "y": 98,
    "w": 20,
    "h": 90,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 7.031567704165354
    },
    "src": "assets/scenes/cemetery_grey/cypress3.png"
   },
   {
    "id": "plane",
    "x": 365,
    "y": 51,
    "w": 115,
    "h": 199,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.7,
     "t": 8,
     "ox": 0.7
    },
    "src": "assets/scenes/cemetery_grey/plane.png"
   },
   {
    "id": "grass",
    "x": 3,
    "y": 237,
    "w": 461,
    "h": 33,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 5,
     "t": 3.6
    },
    "src": "assets/scenes/cemetery_grey/grass.png"
   }
  ]
 },
 "cemetery_night": {
  "flat": "assets/scenes/cemetery_night/flat.png",
  "vignette": [
   0.5,
   "0,4,20"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/cemetery_night/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 53,
    "w": 480,
    "h": 35,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 230
    },
    "src": "assets/scenes/cemetery_night/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 68,
    "w": 480,
    "h": 107,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/cemetery_night/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 158,
    "w": 480,
    "h": 112,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/cemetery_night/land.png"
   },
   {
    "id": "cypress0",
    "x": 7,
    "y": 60,
    "w": 30,
    "h": 132,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 7.003747159615159
    },
    "src": "assets/scenes/cemetery_night/cypress0.png"
   },
   {
    "id": "cypress1",
    "x": 33,
    "y": 92,
    "w": 22,
    "h": 96,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 7.135743513470516
    },
    "src": "assets/scenes/cemetery_night/cypress1.png"
   },
   {
    "id": "cypress2",
    "x": 436,
    "y": 54,
    "w": 32,
    "h": 140,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 7.878534044371918
    },
    "src": "assets/scenes/cemetery_night/cypress2.png"
   },
   {
    "id": "cypress3",
    "x": 416,
    "y": 98,
    "w": 20,
    "h": 90,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 7.800471499795094
    },
    "src": "assets/scenes/cemetery_night/cypress3.png"
   },
   {
    "id": "plane",
    "x": 359,
    "y": 45,
    "w": 121,
    "h": 205,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.7,
     "t": 8,
     "ox": 0.7
    },
    "src": "assets/scenes/cemetery_night/plane.png"
   },
   {
    "id": "grass",
    "x": 0,
    "y": 236,
    "w": 474,
    "h": 34,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 5,
     "t": 3.6
    },
    "src": "assets/scenes/cemetery_night/grass.png"
   }
  ]
 },
 "cemetery_two": {
  "flat": "assets/scenes/cemetery_two/flat.png",
  "vignette": [
   0.4,
   "30,10,20"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/cemetery_two/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 29,
    "w": 480,
    "h": 80,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 230
    },
    "src": "assets/scenes/cemetery_two/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 68,
    "w": 480,
    "h": 107,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/cemetery_two/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 158,
    "w": 480,
    "h": 112,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/cemetery_two/land.png"
   },
   {
    "id": "cypress0",
    "x": 7,
    "y": 60,
    "w": 30,
    "h": 132,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 6.950025607366115
    },
    "src": "assets/scenes/cemetery_two/cypress0.png"
   },
   {
    "id": "cypress1",
    "x": 33,
    "y": 92,
    "w": 22,
    "h": 96,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 6.745495756622404
    },
    "src": "assets/scenes/cemetery_two/cypress1.png"
   },
   {
    "id": "cypress2",
    "x": 436,
    "y": 54,
    "w": 32,
    "h": 140,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 7.524765979265794
    },
    "src": "assets/scenes/cemetery_two/cypress2.png"
   },
   {
    "id": "cypress3",
    "x": 416,
    "y": 98,
    "w": 20,
    "h": 90,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 6.615011135581881
    },
    "src": "assets/scenes/cemetery_two/cypress3.png"
   },
   {
    "id": "plane",
    "x": 364,
    "y": 47,
    "w": 116,
    "h": 203,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.7,
     "t": 8,
     "ox": 0.7
    },
    "src": "assets/scenes/cemetery_two/plane.png"
   },
   {
    "id": "grass",
    "x": 15,
    "y": 237,
    "w": 465,
    "h": 33,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 5,
     "t": 3.6
    },
    "src": "assets/scenes/cemetery_two/grass.png"
   }
  ]
 },
 "china_dock": {
  "flat": "assets/scenes/china_dock/flat.png",
  "vignette": [
   0.45,
   "20,8,20"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/china_dock/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 33,
    "w": 480,
    "h": 53,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 210
    },
    "src": "assets/scenes/china_dock/clouds.png"
   },
   {
    "id": "junk1",
    "x": 66,
    "y": 152,
    "w": 50,
    "h": 41,
    "depth": 0.2,
    "anim": {
     "type": "bob",
     "a": 1.4,
     "r": 0.8,
     "t": 6.733752659987658
    },
    "src": "assets/scenes/china_dock/junk1.png"
   },
   {
    "id": "junk2",
    "x": 286,
    "y": 156,
    "w": 29,
    "h": 24,
    "depth": 0.15,
    "anim": {
     "type": "bob",
     "a": 1.1600000000000001,
     "r": 0.8,
     "t": 6.2601069724187255
    },
    "src": "assets/scenes/china_dock/junk2.png"
   },
   {
    "id": "junk3",
    "x": 167,
    "y": 152,
    "w": 69,
    "h": 58,
    "depth": 0.3,
    "anim": {
     "type": "bob",
     "a": 1.6400000000000001,
     "r": 0.8,
     "t": 6.8323947340250015
    },
    "src": "assets/scenes/china_dock/junk3.png"
   },
   {
    "id": "dock",
    "x": 0,
    "y": 150,
    "w": 480,
    "h": 120,
    "depth": 0.6,
    "anim": null,
    "src": "assets/scenes/china_dock/dock.png"
   }
  ]
 },
 "cs_candle": {
  "flat": "assets/scenes/cs_candle/flat.png",
  "vignette": [
   0.6,
   "0,0,10"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/cs_candle/sky.png"
   },
   {
    "id": "stand",
    "x": 10,
    "y": 87,
    "w": 460,
    "h": 183,
    "depth": 0.5,
    "anim": null,
    "src": "assets/scenes/cs_candle/stand.png"
   }
  ]
 },
 "cs_candle_dawn": {
  "flat": "assets/scenes/cs_candle_dawn/flat.png",
  "vignette": [
   0.35,
   "30,20,20"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/cs_candle_dawn/sky.png"
   },
   {
    "id": "stand",
    "x": 10,
    "y": 143,
    "w": 460,
    "h": 127,
    "depth": 0.5,
    "anim": null,
    "src": "assets/scenes/cs_candle_dawn/stand.png"
   }
  ]
 },
 "cs_seabattle": {
  "flat": "assets/scenes/cs_seabattle/flat.png",
  "vignette": [
   0.5,
   "20,0,10"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/cs_seabattle/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 19,
    "w": 480,
    "h": 96,
    "depth": 0.04,
    "anim": {
     "type": "drift",
     "t": 200
    },
    "src": "assets/scenes/cs_seabattle/clouds.png"
   },
   {
    "id": "coast",
    "x": 0,
    "y": 64,
    "w": 480,
    "h": 93,
    "depth": 0.08,
    "anim": null,
    "src": "assets/scenes/cs_seabattle/coast.png"
   },
   {
    "id": "sea",
    "x": 0,
    "y": 155,
    "w": 480,
    "h": 115,
    "depth": 0.1,
    "anim": {
     "type": "pulse",
     "lo": 0.88,
     "t": 4
    },
    "src": "assets/scenes/cs_seabattle/sea.png"
   }
  ]
 },
 "cs_warships": {
  "flat": "assets/scenes/cs_warships/flat.png",
  "vignette": [
   0.5,
   "20,0,10"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/cs_warships/sky.png"
   },
   {
    "id": "ship_far",
    "x": 286,
    "y": 137,
    "w": 115,
    "h": 69,
    "depth": 0.35,
    "anim": {
     "type": "bob",
     "a": 0.7,
     "t": 5.55
    },
    "src": "assets/scenes/cs_warships/ship_far.png"
   },
   {
    "id": "ship_near",
    "x": 78,
    "y": 123,
    "w": 189,
    "h": 113,
    "depth": 0.6,
    "anim": {
     "type": "bob",
     "a": 0.7,
     "t": 5.9
    },
    "src": "assets/scenes/cs_warships/ship_near.png"
   }
  ]
 },
 "cs_worms": {
  "flat": "assets/scenes/cs_worms/flat.png",
  "vignette": [
   0.6,
   "0,0,0"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/cs_worms/sky.png"
   },
   {
    "id": "tray",
    "x": 10,
    "y": 74,
    "w": 460,
    "h": 192,
    "depth": 0.45,
    "anim": null,
    "src": "assets/scenes/cs_worms/tray.png"
   },
   {
    "id": "worms",
    "x": 52,
    "y": 124,
    "w": 220,
    "h": 121,
    "depth": 0.5,
    "anim": null,
    "src": "assets/scenes/cs_worms/worms.png"
   }
  ]
 },
 "estate_day": {
  "flat": "assets/scenes/estate_day/flat.png",
  "vignette": [
   0.3,
   "30,20,10"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/estate_day/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 8,
    "w": 480,
    "h": 74,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 250
    },
    "src": "assets/scenes/estate_day/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 48,
    "w": 480,
    "h": 104,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/estate_day/far.png"
   },
   {
    "id": "pines",
    "x": 39,
    "y": 96,
    "w": 441,
    "h": 102,
    "depth": 0.3,
    "anim": {
     "type": "sway",
     "a": 0.5,
     "t": 9
    },
    "src": "assets/scenes/estate_day/pines.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 37,
    "w": 480,
    "h": 233,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/estate_day/land.png"
   },
   {
    "id": "reflection",
    "x": 89,
    "y": 228,
    "w": 353,
    "h": 5,
    "depth": 0.35,
    "anim": {
     "type": "pulse",
     "lo": 0.7,
     "t": 4
    },
    "src": "assets/scenes/estate_day/reflection.png"
   },
   {
    "id": "cherry",
    "x": 238,
    "y": 160,
    "w": 48,
    "h": 44,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.4,
     "t": 6
    },
    "src": "assets/scenes/estate_day/cherry.png"
   },
   {
    "id": "maple0",
    "x": 0,
    "y": 82,
    "w": 93,
    "h": 148,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.8,
     "t": 6.2625159081071615,
     "ox": 0.2
    },
    "src": "assets/scenes/estate_day/maple0.png"
   },
   {
    "id": "maple1",
    "x": 400,
    "y": 95,
    "w": 80,
    "h": 141,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.8,
     "t": 7.27151183784008,
     "ox": 0.8
    },
    "src": "assets/scenes/estate_day/maple1.png"
   },
   {
    "id": "grass",
    "x": 0,
    "y": 245,
    "w": 473,
    "h": 25,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 4,
     "t": 3.8
    },
    "src": "assets/scenes/estate_day/grass.png"
   }
  ]
 },
 "estate_room": {
  "flat": "assets/scenes/estate_room/flat.png",
  "vignette": [
   0.4,
   "30,14,0"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/estate_room/sky.png"
   },
   {
    "id": "bamboo",
    "x": 244,
    "y": 0,
    "w": 233,
    "h": 197,
    "depth": 0.25,
    "anim": {
     "type": "sway",
     "a": 1.3,
     "t": 5.5
    },
    "src": "assets/scenes/estate_room/bamboo.png"
   },
   {
    "id": "room",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0.5,
    "anim": null,
    "src": "assets/scenes/estate_room/room.png"
   }
  ]
 },
 "estate_tearoom": {
  "flat": "assets/scenes/estate_tearoom/flat.png",
  "vignette": [
   0.5,
   "16,4,14"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/estate_tearoom/sky.png"
   },
   {
    "id": "blossoms",
    "x": 0,
    "y": 4,
    "w": 266,
    "h": 127,
    "depth": 0.3,
    "anim": {
     "type": "sway",
     "a": 1,
     "t": 6,
     "ox": 0,
     "oy": 0
    },
    "src": "assets/scenes/estate_tearoom/blossoms.png"
   },
   {
    "id": "blossoms2",
    "x": 351,
    "y": 73,
    "w": 68,
    "h": 97,
    "depth": 0.3,
    "anim": {
     "type": "sway",
     "a": 1.6,
     "t": 5
    },
    "src": "assets/scenes/estate_tearoom/blossoms2.png"
   },
   {
    "id": "room",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0.5,
    "anim": null,
    "src": "assets/scenes/estate_tearoom/room.png"
   }
  ]
 },
 "estate_unrest": {
  "flat": "assets/scenes/estate_unrest/flat.png",
  "vignette": [
   0.5,
   "20,4,4"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/estate_unrest/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 20,
    "w": 480,
    "h": 60,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 110
    },
    "src": "assets/scenes/estate_unrest/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 48,
    "w": 480,
    "h": 105,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/estate_unrest/far.png"
   },
   {
    "id": "pines",
    "x": 39,
    "y": 95,
    "w": 441,
    "h": 103,
    "depth": 0.3,
    "anim": {
     "type": "sway",
     "a": 0.5,
     "t": 9
    },
    "src": "assets/scenes/estate_unrest/pines.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 37,
    "w": 480,
    "h": 233,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/estate_unrest/land.png"
   },
   {
    "id": "reflection",
    "x": 89,
    "y": 228,
    "w": 353,
    "h": 21,
    "depth": 0.35,
    "anim": {
     "type": "pulse",
     "lo": 0.7,
     "t": 4
    },
    "src": "assets/scenes/estate_unrest/reflection.png"
   },
   {
    "id": "cherry",
    "x": 239,
    "y": 161,
    "w": 47,
    "h": 43,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.4,
     "t": 6
    },
    "src": "assets/scenes/estate_unrest/cherry.png"
   },
   {
    "id": "maple0",
    "x": 0,
    "y": 82,
    "w": 97,
    "h": 148,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.8,
     "t": 6.407224701251835,
     "ox": 0.2
    },
    "src": "assets/scenes/estate_unrest/maple0.png"
   },
   {
    "id": "maple1",
    "x": 400,
    "y": 96,
    "w": 80,
    "h": 140,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.8,
     "t": 7.091498642694205,
     "ox": 0.8
    },
    "src": "assets/scenes/estate_unrest/maple1.png"
   },
   {
    "id": "grass",
    "x": 0,
    "y": 245,
    "w": 479,
    "h": 25,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 4,
     "t": 3.8
    },
    "src": "assets/scenes/estate_unrest/grass.png"
   }
  ]
 },
 "forest_camp_night": {
  "flat": "assets/scenes/forest_camp_night/flat.png",
  "vignette": [
   0.55,
   "0,0,10"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/forest_camp_night/sky.png"
   },
   {
    "id": "far",
    "x": 18,
    "y": 0,
    "w": 462,
    "h": 200,
    "depth": 0.1,
    "anim": null,
    "src": "assets/scenes/forest_camp_night/far.png"
   },
   {
    "id": "mid",
    "x": 20,
    "y": 0,
    "w": 460,
    "h": 214,
    "depth": 0.25,
    "anim": null,
    "src": "assets/scenes/forest_camp_night/mid.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/forest_camp_night/land.png"
   },
   {
    "id": "banner",
    "x": 302,
    "y": 132,
    "w": 16,
    "h": 44,
    "depth": 0.35,
    "anim": {
     "type": "wave",
     "a": 3,
     "t": 3.2,
     "ox": 0,
     "oy": 0.2
    },
    "src": "assets/scenes/forest_camp_night/banner.png"
   },
   {
    "id": "canopy",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 61,
    "depth": 0.2,
    "anim": {
     "type": "sway",
     "a": 0.6,
     "t": 9,
     "oy": 0
    },
    "src": "assets/scenes/forest_camp_night/canopy.png"
   }
  ]
 },
 "garden_winter": {
  "flat": "assets/scenes/garden_winter/flat.png",
  "vignette": [
   0.4,
   "30,34,60"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/garden_winter/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 12,
    "w": 480,
    "h": 56,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 230
    },
    "src": "assets/scenes/garden_winter/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 77,
    "w": 480,
    "h": 57,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/garden_winter/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 75,
    "w": 480,
    "h": 195,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/garden_winter/land.png"
   },
   {
    "id": "young0",
    "x": 225,
    "y": 110,
    "w": 35,
    "h": 60,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.8,
     "t": 5.404967098496854
    },
    "src": "assets/scenes/garden_winter/young0.png"
   },
   {
    "id": "young1",
    "x": 366,
    "y": 104,
    "w": 38,
    "h": 64,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.8,
     "t": 4.074018527753651
    },
    "src": "assets/scenes/garden_winter/young1.png"
   },
   {
    "id": "young2",
    "x": 410,
    "y": 112,
    "w": 60,
    "h": 66,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.8,
     "t": 4.584482523612678
    },
    "src": "assets/scenes/garden_winter/young2.png"
   },
   {
    "id": "young3",
    "x": 190,
    "y": 125,
    "w": 42,
    "h": 51,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.8,
     "t": 4.912361913826317
    },
    "src": "assets/scenes/garden_winter/young3.png"
   },
   {
    "id": "lime",
    "x": 133,
    "y": 38,
    "w": 107,
    "h": 150,
    "depth": 0.38,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 7
    },
    "src": "assets/scenes/garden_winter/lime.png"
   },
   {
    "id": "flowers",
    "x": 0,
    "y": 216,
    "w": 480,
    "h": 54,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 4,
     "t": 3.6
    },
    "src": "assets/scenes/garden_winter/flowers.png"
   }
  ]
 },
 "hara_kei_estate": {
  "flat": "assets/scenes/hara_kei_estate/flat.png",
  "vignette": [
   0.45,
   "16,4,14"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/hara_kei_estate/sky.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 48,
    "w": 480,
    "h": 104,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/hara_kei_estate/far.png"
   },
   {
    "id": "pines",
    "x": 39,
    "y": 95,
    "w": 441,
    "h": 103,
    "depth": 0.3,
    "anim": {
     "type": "sway",
     "a": 0.5,
     "t": 9
    },
    "src": "assets/scenes/hara_kei_estate/pines.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 37,
    "w": 480,
    "h": 233,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/hara_kei_estate/land.png"
   },
   {
    "id": "reflection",
    "x": 89,
    "y": 228,
    "w": 353,
    "h": 21,
    "depth": 0.35,
    "anim": {
     "type": "pulse",
     "lo": 0.7,
     "t": 4
    },
    "src": "assets/scenes/hara_kei_estate/reflection.png"
   },
   {
    "id": "cherry",
    "x": 238,
    "y": 160,
    "w": 48,
    "h": 44,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.4,
     "t": 6
    },
    "src": "assets/scenes/hara_kei_estate/cherry.png"
   },
   {
    "id": "maple0",
    "x": 0,
    "y": 84,
    "w": 93,
    "h": 146,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.8,
     "t": 6.3098581321537495,
     "ox": 0.2
    },
    "src": "assets/scenes/hara_kei_estate/maple0.png"
   },
   {
    "id": "maple1",
    "x": 400,
    "y": 91,
    "w": 80,
    "h": 145,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.8,
     "t": 7.796579853631556,
     "ox": 0.8
    },
    "src": "assets/scenes/hara_kei_estate/maple1.png"
   },
   {
    "id": "grass",
    "x": 4,
    "y": 245,
    "w": 475,
    "h": 25,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 4,
     "t": 3.8
    },
    "src": "assets/scenes/hara_kei_estate/grass.png"
   }
  ]
 },
 "helene_garden": {
  "flat": "assets/scenes/helene_garden/flat.png",
  "vignette": [
   0.35,
   "30,20,10"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/helene_garden/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 25,
    "w": 480,
    "h": 40,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 230
    },
    "src": "assets/scenes/helene_garden/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 95,
    "w": 480,
    "h": 39,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/helene_garden/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 75,
    "w": 480,
    "h": 195,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/helene_garden/land.png"
   },
   {
    "id": "young0",
    "x": 235,
    "y": 131,
    "w": 31,
    "h": 39,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.8,
     "t": 5.948534244671464
    },
    "src": "assets/scenes/helene_garden/young0.png"
   },
   {
    "id": "young1",
    "x": 374,
    "y": 123,
    "w": 32,
    "h": 45,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.8,
     "t": 4.413549180608243
    },
    "src": "assets/scenes/helene_garden/young1.png"
   },
   {
    "id": "young2",
    "x": 421,
    "y": 130,
    "w": 37,
    "h": 48,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.8,
     "t": 5.98775839060545
    },
    "src": "assets/scenes/helene_garden/young2.png"
   },
   {
    "id": "young3",
    "x": 200,
    "y": 141,
    "w": 24,
    "h": 35,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.8,
     "t": 5.384776239283383
    },
    "src": "assets/scenes/helene_garden/young3.png"
   },
   {
    "id": "lime",
    "x": 124,
    "y": 73,
    "w": 122,
    "h": 115,
    "depth": 0.38,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 7
    },
    "src": "assets/scenes/helene_garden/lime.png"
   },
   {
    "id": "flowers",
    "x": 14,
    "y": 218,
    "w": 466,
    "h": 52,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 4,
     "t": 3.6
    },
    "src": "assets/scenes/helene_garden/flowers.png"
   }
  ]
 },
 "helene_sickroom": {
  "flat": "assets/scenes/helene_sickroom/flat.png",
  "vignette": [
   0.5,
   "20,20,40"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/helene_sickroom/sky.png"
   },
   {
    "id": "curtainL",
    "x": 140,
    "y": 52,
    "w": 16,
    "h": 116,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 1.4,
     "t": 6,
     "oy": 0
    },
    "src": "assets/scenes/helene_sickroom/curtainL.png"
   },
   {
    "id": "curtainR",
    "x": 234,
    "y": 52,
    "w": 16,
    "h": 116,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 1.2,
     "t": 7,
     "oy": 0
    },
    "src": "assets/scenes/helene_sickroom/curtainR.png"
   }
  ]
 },
 "japan_coast": {
  "flat": "assets/scenes/japan_coast/flat.png",
  "vignette": [
   0.35,
   "10,10,30"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/japan_coast/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 51,
    "w": 480,
    "h": 50,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 220
    },
    "src": "assets/scenes/japan_coast/clouds.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 110,
    "w": 480,
    "h": 160,
    "depth": 0.4,
    "anim": null,
    "src": "assets/scenes/japan_coast/land.png"
   },
   {
    "id": "pine1",
    "x": 30,
    "y": 4,
    "w": 88,
    "h": 108,
    "depth": 0.4,
    "anim": {
     "type": "sway",
     "a": 1.2,
     "t": 7,
     "ox": 0.3
    },
    "src": "assets/scenes/japan_coast/pine1.png"
   },
   {
    "id": "pine2",
    "x": 117,
    "y": 76,
    "w": 54,
    "h": 67,
    "depth": 0.4,
    "anim": {
     "type": "sway",
     "a": 1.5,
     "t": 6,
     "ox": 0.3
    },
    "src": "assets/scenes/japan_coast/pine2.png"
   },
   {
    "id": "pine3",
    "x": 337,
    "y": 156,
    "w": 21,
    "h": 25,
    "depth": 0.4,
    "anim": {
     "type": "sway",
     "a": 2,
     "t": 5
    },
    "src": "assets/scenes/japan_coast/pine3.png"
   }
  ]
 },
 "japan_path": {
  "flat": "assets/scenes/japan_path/flat.png",
  "vignette": [
   0.35,
   "10,20,0"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/japan_path/sky.png"
   },
   {
    "id": "far",
    "x": 132,
    "y": 23,
    "w": 211,
    "h": 243,
    "depth": 0.1,
    "anim": null,
    "src": "assets/scenes/japan_path/far.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 240,
    "depth": 0.2,
    "anim": null,
    "src": "assets/scenes/japan_path/mid.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/japan_path/land.png"
   },
   {
    "id": "leaves",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 70,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 1.2,
     "t": 6,
     "oy": 0
    },
    "src": "assets/scenes/japan_path/leaves.png"
   },
   {
    "id": "flowers",
    "x": 0,
    "y": 218,
    "w": 477,
    "h": 52,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 4,
     "t": 3.4
    },
    "src": "assets/scenes/japan_path/flowers.png"
   }
  ]
 },
 "joncour_bedroom": {
  "flat": "assets/scenes/joncour_bedroom/flat.png",
  "vignette": [
   0.5,
   "4,6,24"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/joncour_bedroom/sky.png"
   },
   {
    "id": "curtain176",
    "x": 174,
    "y": 46,
    "w": 18,
    "h": 114,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 6.197673924732953,
     "oy": 0
    },
    "src": "assets/scenes/joncour_bedroom/curtain176.png"
   },
   {
    "id": "curtain304",
    "x": 288,
    "y": 46,
    "w": 18,
    "h": 114,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 0.9,
     "t": 6.201709651853889,
     "oy": 0
    },
    "src": "assets/scenes/joncour_bedroom/curtain304.png"
   },
   {
    "id": "bed",
    "x": 104,
    "y": 150,
    "w": 322,
    "h": 114,
    "depth": 0.55,
    "anim": null,
    "src": "assets/scenes/joncour_bedroom/bed.png"
   }
  ]
 },
 "joncour_home": {
  "flat": "assets/scenes/joncour_home/flat.png",
  "vignette": [
   0.3,
   "60,34,14"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/joncour_home/sky.png"
   }
  ]
 },
 "journey_map": {
  "flat": "assets/scenes/journey_map/flat.png",
  "vignette": [
   0.25,
   "30,14,0"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/journey_map/sky.png"
   }
  ]
 },
 "jp_gate": {
  "flat": "assets/scenes/jp_gate/flat.png",
  "vignette": [
   0.55,
   "20,4,10"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/jp_gate/sky.png"
   },
   {
    "id": "yotei",
    "x": 151,
    "y": 65,
    "w": 299,
    "h": 85,
    "depth": 0.04,
    "anim": null,
    "src": "assets/scenes/jp_gate/yotei.png"
   },
   {
    "id": "gate",
    "x": 0,
    "y": 57,
    "w": 480,
    "h": 213,
    "depth": 0.15,
    "anim": null,
    "src": "assets/scenes/jp_gate/gate.png"
   },
   {
    "id": "trees",
    "x": 2,
    "y": 83,
    "w": 471,
    "h": 127,
    "depth": 0.2,
    "anim": {
     "type": "sway",
     "a": 1,
     "t": 7
    },
    "src": "assets/scenes/jp_gate/trees.png"
   }
  ]
 },
 "jp_reveal": {
  "flat": "assets/scenes/jp_reveal/flat.png",
  "vignette": [
   0.42,
   "30,6,14"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/jp_reveal/sky.png"
   },
   {
    "id": "clouds_far",
    "x": 0,
    "y": 36,
    "w": 480,
    "h": 31,
    "depth": 0.02,
    "anim": {
     "type": "drift",
     "t": 900
    },
    "src": "assets/scenes/jp_reveal/clouds_far.png"
   },
   {
    "id": "clouds_frame",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 195,
    "depth": 0.03,
    "anim": {
     "type": "drift",
     "t": 2400
    },
    "src": "assets/scenes/jp_reveal/clouds_frame.png"
   },
   {
    "id": "yotei",
    "x": 90,
    "y": 51,
    "w": 390,
    "h": 133,
    "depth": 0.05,
    "anim": null,
    "src": "assets/scenes/jp_reveal/yotei.png"
   },
   {
    "id": "town",
    "x": 46,
    "y": 50,
    "w": 300,
    "h": 164,
    "depth": 0.1,
    "anim": null,
    "src": "assets/scenes/jp_reveal/town.png"
   },
   {
    "id": "plain",
    "x": 0,
    "y": 196,
    "w": 480,
    "h": 26,
    "depth": 0.14,
    "anim": null,
    "src": "assets/scenes/jp_reveal/plain.png"
   },
   {
    "id": "lake",
    "x": 0,
    "y": 214,
    "w": 480,
    "h": 56,
    "depth": 0.2,
    "anim": {
     "type": "pulse",
     "lo": 0.85,
     "t": 5
    },
    "src": "assets/scenes/jp_reveal/lake.png"
   },
   {
    "id": "blossom_front",
    "x": 0,
    "y": 0,
    "w": 166,
    "h": 61,
    "depth": 0.4,
    "anim": {
     "type": "sway",
     "a": 1.2,
     "t": 6,
     "ox": 0,
     "oy": 0
    },
    "src": "assets/scenes/jp_reveal/blossom_front.png"
   },
   {
    "id": "blossom_front2",
    "x": 378,
    "y": 0,
    "w": 102,
    "h": 55,
    "depth": 0.4,
    "anim": {
     "type": "sway",
     "a": 1.5,
     "t": 7,
     "ox": 1,
     "oy": 0
    },
    "src": "assets/scenes/jp_reveal/blossom_front2.png"
   }
  ]
 },
 "jp_sakura_road": {
  "flat": "assets/scenes/jp_sakura_road/flat.png",
  "vignette": [
   0.45,
   "30,6,14"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/jp_sakura_road/sky.png"
   },
   {
    "id": "yotei",
    "x": 121,
    "y": 90,
    "w": 239,
    "h": 66,
    "depth": 0.04,
    "anim": null,
    "src": "assets/scenes/jp_sakura_road/yotei.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 150,
    "w": 480,
    "h": 120,
    "depth": 0.2,
    "anim": null,
    "src": "assets/scenes/jp_sakura_road/ground.png"
   },
   {
    "id": "lanterns",
    "x": 68,
    "y": 131,
    "w": 344,
    "h": 127,
    "depth": 0.2,
    "anim": null,
    "src": "assets/scenes/jp_sakura_road/lanterns.png"
   },
   {
    "id": "trees_far",
    "x": 69,
    "y": 114,
    "w": 334,
    "h": 94,
    "depth": 0.25,
    "anim": {
     "type": "sway",
     "a": 0.6,
     "t": 8
    },
    "src": "assets/scenes/jp_sakura_road/trees_far.png"
   },
   {
    "id": "trees_near",
    "x": 0,
    "y": 84,
    "w": 480,
    "h": 163,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 1.4,
     "t": 6
    },
    "src": "assets/scenes/jp_sakura_road/trees_near.png"
   }
  ]
 },
 "lavilledieu": {
  "flat": "assets/scenes/lavilledieu/flat.png",
  "vignette": [
   0.18,
   "40,30,20"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/lavilledieu/sky.png"
   },
   {
    "id": "clouds_high",
    "x": 0,
    "y": 7,
    "w": 480,
    "h": 45,
    "depth": 0.02,
    "anim": {
     "type": "drift",
     "t": 700
    },
    "src": "assets/scenes/lavilledieu/clouds_high.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 23,
    "w": 480,
    "h": 55,
    "depth": 0.04,
    "anim": {
     "type": "drift",
     "t": 420
    },
    "src": "assets/scenes/lavilledieu/clouds.png"
   },
   {
    "id": "peaks",
    "x": 0,
    "y": 30,
    "w": 480,
    "h": 128,
    "depth": 0.01,
    "anim": null,
    "src": "assets/scenes/lavilledieu/peaks.png"
   },
   {
    "id": "range",
    "x": 0,
    "y": 59,
    "w": 480,
    "h": 117,
    "depth": 0.03,
    "anim": null,
    "src": "assets/scenes/lavilledieu/range.png"
   },
   {
    "id": "hills",
    "x": 0,
    "y": 100,
    "w": 480,
    "h": 90,
    "depth": 0.06,
    "anim": null,
    "src": "assets/scenes/lavilledieu/hills.png"
   },
   {
    "id": "sails0",
    "x": 39,
    "y": 89,
    "w": 33,
    "h": 33,
    "depth": 0.06,
    "anim": {
     "type": "spin",
     "t": 10,
     "ox": 0.5,
     "oy": 0.5
    },
    "src": "assets/scenes/lavilledieu/sails0.png"
   },
   {
    "id": "sails1",
    "x": 134,
    "y": 88,
    "w": 30,
    "h": 31,
    "depth": 0.06,
    "anim": {
     "type": "spin",
     "t": 12,
     "ox": 0.5,
     "oy": 0.5
    },
    "src": "assets/scenes/lavilledieu/sails1.png"
   },
   {
    "id": "hill",
    "x": 150,
    "y": 14,
    "w": 330,
    "h": 182,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/lavilledieu/hill.png"
   },
   {
    "id": "town",
    "x": 0,
    "y": 92,
    "w": 480,
    "h": 107,
    "depth": 0.2,
    "anim": null,
    "src": "assets/scenes/lavilledieu/town.png"
   },
   {
    "id": "wheel",
    "x": 97,
    "y": 173,
    "w": 31,
    "h": 31,
    "depth": 0.2,
    "anim": {
     "type": "spin",
     "t": 7,
     "ox": 0.5,
     "oy": 0.5
    },
    "src": "assets/scenes/lavilledieu/wheel.png"
   },
   {
    "id": "river",
    "x": 0,
    "y": 196,
    "w": 480,
    "h": 50,
    "depth": 0.3,
    "anim": null,
    "src": "assets/scenes/lavilledieu/river.png"
   },
   {
    "id": "lighthouse",
    "x": 423,
    "y": 112,
    "w": 56,
    "h": 126,
    "depth": 0.31,
    "anim": null,
    "src": "assets/scenes/lavilledieu/lighthouse.png"
   },
   {
    "id": "boat250",
    "x": 228,
    "y": 178,
    "w": 46,
    "h": 38,
    "depth": 0.32,
    "anim": {
     "type": "bob",
     "a": 0.8,
     "t": 4.4
    },
    "src": "assets/scenes/lavilledieu/boat250.png"
   },
   {
    "id": "boat380",
    "x": 363,
    "y": 214,
    "w": 36,
    "h": 14,
    "depth": 0.32,
    "anim": {
     "type": "bob",
     "a": 0.8,
     "t": 5.2
    },
    "src": "assets/scenes/lavilledieu/boat380.png"
   },
   {
    "id": "bank",
    "x": 0,
    "y": 230,
    "w": 480,
    "h": 40,
    "depth": 0.6,
    "anim": {
     "type": "sway",
     "a": 1.2,
     "t": 4.6,
     "oy": 1
    },
    "src": "assets/scenes/lavilledieu/bank.png"
   }
  ]
 },
 "op_autumn": {
  "flat": "assets/scenes/op_autumn/flat.png",
  "vignette": [
   0.3,
   "40,20,10"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/op_autumn/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 36,
    "depth": 0.03,
    "anim": {
     "type": "drift",
     "t": 420
    },
    "src": "assets/scenes/op_autumn/clouds.png"
   },
   {
    "id": "cliff",
    "x": 134,
    "y": 20,
    "w": 279,
    "h": 182,
    "depth": 0.07,
    "anim": null,
    "src": "assets/scenes/op_autumn/cliff.png"
   },
   {
    "id": "mist",
    "x": 0,
    "y": 149,
    "w": 480,
    "h": 46,
    "depth": 0.09,
    "anim": {
     "type": "drift",
     "t": 240
    },
    "src": "assets/scenes/op_autumn/mist.png"
   },
   {
    "id": "valley",
    "x": 0,
    "y": 174,
    "w": 480,
    "h": 76,
    "depth": 0.13,
    "anim": null,
    "src": "assets/scenes/op_autumn/valley.png"
   },
   {
    "id": "knoll",
    "x": 150,
    "y": 208,
    "w": 330,
    "h": 33,
    "depth": 0.22,
    "anim": null,
    "src": "assets/scenes/op_autumn/knoll.png"
   },
   {
    "id": "rider",
    "x": 282,
    "y": 145,
    "w": 55,
    "h": 113,
    "depth": 0.3,
    "anim": {
     "type": "bob",
     "a": 0.35,
     "t": 3.8
    },
    "src": "assets/scenes/op_autumn/rider.png"
   },
   {
    "id": "maples_left",
    "x": 0,
    "y": 0,
    "w": 148,
    "h": 270,
    "depth": 0.45,
    "anim": {
     "type": "sway",
     "a": 0.7,
     "t": 6,
     "oy": 1
    },
    "src": "assets/scenes/op_autumn/maples_left.png"
   },
   {
    "id": "maples_right",
    "x": 328,
    "y": 0,
    "w": 152,
    "h": 270,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 0.6,
     "t": 6.8,
     "oy": 1
    },
    "src": "assets/scenes/op_autumn/maples_right.png"
   },
   {
    "id": "brush",
    "x": 0,
    "y": 219,
    "w": 480,
    "h": 51,
    "depth": 0.72,
    "anim": {
     "type": "sway",
     "a": 1.2,
     "t": 4.6,
     "oy": 1
    },
    "src": "assets/scenes/op_autumn/brush.png"
   }
  ]
 },
 "op_gold": {
  "flat": "assets/scenes/op_gold/flat.png",
  "vignette": [
   0.28,
   "60,40,10"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/op_gold/sky.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 91,
    "w": 480,
    "h": 50,
    "depth": 0.04,
    "anim": null,
    "src": "assets/scenes/op_gold/far.png"
   },
   {
    "id": "hill",
    "x": 0,
    "y": 72,
    "w": 480,
    "h": 89,
    "depth": 0.08,
    "anim": null,
    "src": "assets/scenes/op_gold/hill.png"
   },
   {
    "id": "haze",
    "x": 0,
    "y": 136,
    "w": 480,
    "h": 23,
    "depth": 0.1,
    "anim": {
     "type": "drift",
     "t": 300
    },
    "src": "assets/scenes/op_gold/haze.png"
   },
   {
    "id": "field",
    "x": 0,
    "y": 150,
    "w": 480,
    "h": 120,
    "depth": 0.14,
    "anim": null,
    "src": "assets/scenes/op_gold/field.png"
   },
   {
    "id": "near",
    "x": 0,
    "y": 226,
    "w": 480,
    "h": 44,
    "depth": 0.55,
    "anim": {
     "type": "sway",
     "a": 1.4,
     "t": 4.4,
     "oy": 1
    },
    "src": "assets/scenes/op_gold/near.png"
   }
  ]
 },
 "op_mountain": {
  "flat": "assets/scenes/op_mountain/flat.png",
  "vignette": [
   0.32,
   "20,22,30"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/op_mountain/sky.png"
   },
   {
    "id": "storm_high",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 64,
    "depth": 0.02,
    "anim": {
     "type": "drift",
     "t": 560
    },
    "src": "assets/scenes/op_mountain/storm_high.png"
   },
   {
    "id": "storm_low",
    "x": 0,
    "y": 68,
    "w": 480,
    "h": 23,
    "depth": 0.04,
    "anim": {
     "type": "drift",
     "t": 380
    },
    "src": "assets/scenes/op_mountain/storm_low.png"
   },
   {
    "id": "mountain",
    "x": 70,
    "y": 75,
    "w": 410,
    "h": 107,
    "depth": 0.06,
    "anim": null,
    "src": "assets/scenes/op_mountain/mountain.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 160,
    "w": 480,
    "h": 36,
    "depth": 0.1,
    "anim": null,
    "src": "assets/scenes/op_mountain/far.png"
   },
   {
    "id": "plain",
    "x": 0,
    "y": 186,
    "w": 480,
    "h": 40,
    "depth": 0.16,
    "anim": null,
    "src": "assets/scenes/op_mountain/plain.png"
   },
   {
    "id": "near",
    "x": 0,
    "y": 214,
    "w": 480,
    "h": 56,
    "depth": 0.28,
    "anim": {
     "type": "sway",
     "a": 0.5,
     "t": 5,
     "oy": 1
    },
    "src": "assets/scenes/op_mountain/near.png"
   },
   {
    "id": "rider",
    "x": 84,
    "y": 168,
    "w": 62,
    "h": 73,
    "depth": 0.3,
    "anim": {
     "type": "bob",
     "a": 0.4,
     "t": 3.4
    },
    "src": "assets/scenes/op_mountain/rider.png"
   },
   {
    "id": "front",
    "x": 4,
    "y": 226,
    "w": 476,
    "h": 44,
    "depth": 0.7,
    "anim": {
     "type": "sway",
     "a": 1.6,
     "t": 4.2,
     "oy": 1
    },
    "src": "assets/scenes/op_mountain/front.png"
   }
  ]
 },
 "op_sakura": {
  "flat": "assets/scenes/op_sakura/flat.png",
  "vignette": [
   0.25,
   "30,20,40"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/op_sakura/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 25,
    "w": 480,
    "h": 42,
    "depth": 0.03,
    "anim": {
     "type": "drift",
     "t": 360
    },
    "src": "assets/scenes/op_sakura/clouds.png"
   },
   {
    "id": "mountains",
    "x": 0,
    "y": 112,
    "w": 480,
    "h": 61,
    "depth": 0.05,
    "anim": null,
    "src": "assets/scenes/op_sakura/mountains.png"
   },
   {
    "id": "castle",
    "x": 0,
    "y": 125,
    "w": 480,
    "h": 55,
    "depth": 0.08,
    "anim": null,
    "src": "assets/scenes/op_sakura/castle.png"
   },
   {
    "id": "field",
    "x": 0,
    "y": 176,
    "w": 480,
    "h": 76,
    "depth": 0.16,
    "anim": null,
    "src": "assets/scenes/op_sakura/field.png"
   },
   {
    "id": "trees_mid",
    "x": 22,
    "y": 130,
    "w": 436,
    "h": 74,
    "depth": 0.24,
    "anim": {
     "type": "sway",
     "a": 0.5,
     "t": 6.4,
     "oy": 1
    },
    "src": "assets/scenes/op_sakura/trees_mid.png"
   },
   {
    "id": "rider",
    "x": 164,
    "y": 156,
    "w": 49,
    "h": 101,
    "depth": 0.32,
    "anim": {
     "type": "bob",
     "a": 0.35,
     "t": 3.6
    },
    "src": "assets/scenes/op_sakura/rider.png"
   },
   {
    "id": "trees_big",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 0.4,
     "t": 7,
     "oy": 1
    },
    "src": "assets/scenes/op_sakura/trees_big.png"
   },
   {
    "id": "floor",
    "x": 0,
    "y": 243,
    "w": 480,
    "h": 27,
    "depth": 0.75,
    "anim": null,
    "src": "assets/scenes/op_sakura/floor.png"
   }
  ]
 },
 "road_east": {
  "flat": "assets/scenes/road_east/flat.png",
  "vignette": [
   0.4,
   "20,10,20"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/road_east/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 13,
    "w": 480,
    "h": 100,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 200
    },
    "src": "assets/scenes/road_east/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 121,
    "w": 480,
    "h": 34,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/road_east/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 136,
    "w": 480,
    "h": 134,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/road_east/land.png"
   },
   {
    "id": "birch0",
    "x": 0,
    "y": 69,
    "w": 74,
    "h": 201,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 5.906208254629746
    },
    "src": "assets/scenes/road_east/birch0.png"
   },
   {
    "id": "birch1",
    "x": 2,
    "y": 72,
    "w": 80,
    "h": 193,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 4.6875163917429745
    },
    "src": "assets/scenes/road_east/birch1.png"
   },
   {
    "id": "birch2",
    "x": 28,
    "y": 79,
    "w": 74,
    "h": 176,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 6.670380178722553
    },
    "src": "assets/scenes/road_east/birch2.png"
   },
   {
    "id": "birch3",
    "x": 63,
    "y": 87,
    "w": 60,
    "h": 155,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 4.73384784872178
    },
    "src": "assets/scenes/road_east/birch3.png"
   },
   {
    "id": "birch4",
    "x": 102,
    "y": 104,
    "w": 52,
    "h": 120,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 6.329035182017833
    },
    "src": "assets/scenes/road_east/birch4.png"
   },
   {
    "id": "birch5",
    "x": 148,
    "y": 113,
    "w": 38,
    "h": 92,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 5.8755431526806206
    },
    "src": "assets/scenes/road_east/birch5.png"
   },
   {
    "id": "birch6",
    "x": 202,
    "y": 128,
    "w": 22,
    "h": 55,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 6.694971340359189
    },
    "src": "assets/scenes/road_east/birch6.png"
   },
   {
    "id": "birch7",
    "x": 259,
    "y": 145,
    "w": 6,
    "h": 13,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 6.8370987037196755
    },
    "src": "assets/scenes/road_east/birch7.png"
   },
   {
    "id": "grass",
    "x": 0,
    "y": 234,
    "w": 480,
    "h": 36,
    "depth": 0.6,
    "anim": {
     "type": "sway",
     "a": 5,
     "t": 3.4
    },
    "src": "assets/scenes/road_east/grass.png"
   }
  ]
 },
 "road_rain": {
  "flat": "assets/scenes/road_rain/flat.png",
  "vignette": [
   0.55,
   "5,8,16"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/road_rain/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 106,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 90
    },
    "src": "assets/scenes/road_rain/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 121,
    "w": 480,
    "h": 34,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/road_rain/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 150,
    "w": 480,
    "h": 120,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/road_rain/land.png"
   },
   {
    "id": "birch0",
    "x": 0,
    "y": 69,
    "w": 74,
    "h": 201,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 2.4,
     "t": 5.906208254629746
    },
    "src": "assets/scenes/road_rain/birch0.png"
   },
   {
    "id": "birch1",
    "x": 2,
    "y": 72,
    "w": 80,
    "h": 193,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 2.4,
     "t": 4.6875163917429745
    },
    "src": "assets/scenes/road_rain/birch1.png"
   },
   {
    "id": "birch2",
    "x": 28,
    "y": 79,
    "w": 74,
    "h": 176,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 2.4,
     "t": 6.670380178722553
    },
    "src": "assets/scenes/road_rain/birch2.png"
   },
   {
    "id": "birch3",
    "x": 63,
    "y": 87,
    "w": 60,
    "h": 155,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 2.4,
     "t": 4.73384784872178
    },
    "src": "assets/scenes/road_rain/birch3.png"
   },
   {
    "id": "birch4",
    "x": 102,
    "y": 104,
    "w": 52,
    "h": 120,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 2.4,
     "t": 6.329035182017833
    },
    "src": "assets/scenes/road_rain/birch4.png"
   },
   {
    "id": "birch5",
    "x": 148,
    "y": 113,
    "w": 38,
    "h": 92,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 2.4,
     "t": 5.8755431526806206
    },
    "src": "assets/scenes/road_rain/birch5.png"
   },
   {
    "id": "birch6",
    "x": 202,
    "y": 128,
    "w": 22,
    "h": 55,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 2.4,
     "t": 6.694971340359189
    },
    "src": "assets/scenes/road_rain/birch6.png"
   },
   {
    "id": "birch7",
    "x": 259,
    "y": 145,
    "w": 6,
    "h": 13,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 2.4,
     "t": 6.8370987037196755
    },
    "src": "assets/scenes/road_rain/birch7.png"
   },
   {
    "id": "grass",
    "x": 0,
    "y": 234,
    "w": 480,
    "h": 36,
    "depth": 0.6,
    "anim": {
     "type": "sway",
     "a": 9,
     "t": 3.4
    },
    "src": "assets/scenes/road_rain/grass.png"
   }
  ]
 },
 "road_winter": {
  "flat": "assets/scenes/road_winter/flat.png",
  "vignette": [
   0.35,
   "40,40,70"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/road_winter/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 11,
    "w": 480,
    "h": 100,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 200
    },
    "src": "assets/scenes/road_winter/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 121,
    "w": 480,
    "h": 34,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/road_winter/far.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 149,
    "w": 480,
    "h": 121,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/road_winter/land.png"
   },
   {
    "id": "birch0",
    "x": 0,
    "y": 26,
    "w": 95,
    "h": 244,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 4.608459906768985
    },
    "src": "assets/scenes/road_winter/birch0.png"
   },
   {
    "id": "birch1",
    "x": 0,
    "y": 43,
    "w": 93,
    "h": 222,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 6.513281753752381
    },
    "src": "assets/scenes/road_winter/birch1.png"
   },
   {
    "id": "birch2",
    "x": 2,
    "y": 53,
    "w": 118,
    "h": 202,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 5.44241441518534
    },
    "src": "assets/scenes/road_winter/birch2.png"
   },
   {
    "id": "birch3",
    "x": 30,
    "y": 63,
    "w": 106,
    "h": 179,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 6.8336029454367235
    },
    "src": "assets/scenes/road_winter/birch3.png"
   },
   {
    "id": "birch4",
    "x": 102,
    "y": 82,
    "w": 64,
    "h": 142,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 6.829763461602852
    },
    "src": "assets/scenes/road_winter/birch4.png"
   },
   {
    "id": "birch5",
    "x": 139,
    "y": 94,
    "w": 61,
    "h": 111,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 5.9707776822615415
    },
    "src": "assets/scenes/road_winter/birch5.png"
   },
   {
    "id": "birch6",
    "x": 196,
    "y": 118,
    "w": 36,
    "h": 65,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 5.257304765284061
    },
    "src": "assets/scenes/road_winter/birch6.png"
   },
   {
    "id": "birch7",
    "x": 256,
    "y": 140,
    "w": 7,
    "h": 18,
    "depth": 0.35,
    "anim": {
     "type": "sway",
     "a": 1.1,
     "t": 6.68249220517464
    },
    "src": "assets/scenes/road_winter/birch7.png"
   },
   {
    "id": "grass",
    "x": 0,
    "y": 236,
    "w": 475,
    "h": 34,
    "depth": 0.6,
    "anim": {
     "type": "sway",
     "a": 5,
     "t": 3.4
    },
    "src": "assets/scenes/road_winter/grass.png"
   }
  ]
 },
 "silk_mill": {
  "flat": "assets/scenes/silk_mill/flat.png",
  "vignette": [
   0.35,
   "30,16,0"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/silk_mill/sky.png"
   },
   {
    "id": "skeins",
    "x": 153,
    "y": 41,
    "w": 177,
    "h": 18,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 2.2,
     "t": 4.5,
     "oy": 0
    },
    "src": "assets/scenes/silk_mill/skeins.png"
   },
   {
    "id": "wheel",
    "x": 225,
    "y": 133,
    "w": 30,
    "h": 30,
    "depth": 0.5,
    "anim": {
     "type": "spin",
     "t": 9,
     "ox": 0.5,
     "oy": 0.5
    },
    "src": "assets/scenes/silk_mill/wheel.png"
   }
  ]
 },
 "silk_mill_empty": {
  "flat": "assets/scenes/silk_mill_empty/flat.png",
  "vignette": [
   0.55,
   "10,14,24"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/silk_mill_empty/sky.png"
   },
   {
    "id": "skeins",
    "x": 156,
    "y": 41,
    "w": 172,
    "h": 18,
    "depth": 0.5,
    "anim": {
     "type": "sway",
     "a": 3.5,
     "t": 6,
     "oy": 0
    },
    "src": "assets/scenes/silk_mill_empty/skeins.png"
   }
  ]
 },
 "smuggler_boat": {
  "flat": "assets/scenes/smuggler_boat/flat.png",
  "vignette": [
   0.5,
   "0,4,20"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/smuggler_boat/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 114,
    "w": 480,
    "h": 12,
    "depth": 0.04,
    "anim": {
     "type": "drift",
     "t": 300
    },
    "src": "assets/scenes/smuggler_boat/clouds.png"
   },
   {
    "id": "sea",
    "x": 0,
    "y": 126,
    "w": 480,
    "h": 144,
    "depth": 0.1,
    "anim": null,
    "src": "assets/scenes/smuggler_boat/sea.png"
   },
   {
    "id": "deck",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0.8,
    "anim": {
     "type": "bob",
     "a": 1.6,
     "r": 0.55,
     "t": 7,
     "oy": 1
    },
    "src": "assets/scenes/smuggler_boat/deck.png"
   }
  ]
 },
 "the_cup": {
  "flat": "assets/scenes/the_cup/flat.png",
  "vignette": [
   0.55,
   "6,4,20"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/the_cup/sky.png"
   },
   {
    "id": "table",
    "x": 0,
    "y": 132,
    "w": 480,
    "h": 138,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/the_cup/table.png"
   },
   {
    "id": "sleeve",
    "x": 401,
    "y": 0,
    "w": 79,
    "h": 267,
    "depth": 0.6,
    "anim": {
     "type": "sway",
     "a": 0.5,
     "t": 7,
     "ox": 1,
     "oy": 0
    },
    "src": "assets/scenes/the_cup/sleeve.png"
   },
   {
    "id": "cup",
    "x": 179,
    "y": 138,
    "w": 142,
    "h": 106,
    "depth": 0.55,
    "anim": null,
    "src": "assets/scenes/the_cup/cup.png"
   }
  ]
 },
 "the_glove": {
  "flat": "assets/scenes/the_glove/flat.png",
  "vignette": [
   0.45,
   "30,14,0"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/the_glove/sky.png"
   },
   {
    "id": "things",
    "x": 70,
    "y": 50,
    "w": 392,
    "h": 200,
    "depth": 0.45,
    "anim": null,
    "src": "assets/scenes/the_glove/things.png"
   },
   {
    "id": "glove",
    "x": 154,
    "y": 118,
    "w": 111,
    "h": 127,
    "depth": 0.6,
    "anim": null,
    "src": "assets/scenes/the_glove/glove.png"
   }
  ]
 },
 "the_letter": {
  "flat": "assets/scenes/the_letter/flat.png",
  "vignette": [
   0.5,
   "20,8,0"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/the_letter/sky.png"
   },
   {
    "id": "sheets",
    "x": 31,
    "y": 35,
    "w": 415,
    "h": 235,
    "depth": 0.45,
    "anim": null,
    "src": "assets/scenes/the_letter/sheets.png"
   },
   {
    "id": "lamp",
    "x": 404,
    "y": 40,
    "w": 52,
    "h": 116,
    "depth": 0.6,
    "anim": null,
    "src": "assets/scenes/the_letter/lamp.png"
   }
  ]
 },
 "war_field": {
  "flat": "assets/scenes/war_field/flat.png",
  "vignette": [
   0.4,
   "20,10,6"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/war_field/sky.png"
   },
   {
    "id": "smoke_sky",
    "x": 0,
    "y": 31,
    "w": 480,
    "h": 54,
    "depth": 0.04,
    "anim": {
     "type": "drift",
     "t": 220
    },
    "src": "assets/scenes/war_field/smoke_sky.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 106,
    "w": 480,
    "h": 164,
    "depth": 0.07,
    "anim": null,
    "src": "assets/scenes/war_field/far.png"
   },
   {
    "id": "smoke",
    "x": 52,
    "y": 55,
    "w": 361,
    "h": 127,
    "depth": 0.1,
    "anim": null,
    "src": "assets/scenes/war_field/smoke.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 146,
    "w": 480,
    "h": 124,
    "depth": 0.25,
    "anim": null,
    "src": "assets/scenes/war_field/land.png"
   },
   {
    "id": "banner362",
    "x": 363,
    "y": 150,
    "w": 9,
    "h": 28,
    "depth": 0.26,
    "anim": {
     "type": "wave",
     "a": 1,
     "t": 2.0520367255434397
    },
    "src": "assets/scenes/war_field/banner362.png"
   },
   {
    "id": "banner388",
    "x": 389,
    "y": 150,
    "w": 9,
    "h": 28,
    "depth": 0.26,
    "anim": {
     "type": "wave",
     "a": 1,
     "t": 2.020845962688327
    },
    "src": "assets/scenes/war_field/banner388.png"
   },
   {
    "id": "banner414",
    "x": 415,
    "y": 150,
    "w": 9,
    "h": 28,
    "depth": 0.26,
    "anim": {
     "type": "wave",
     "a": 1,
     "t": 1.4230985244736074
    },
    "src": "assets/scenes/war_field/banner414.png"
   },
   {
    "id": "banner446",
    "x": 447,
    "y": 150,
    "w": 9,
    "h": 28,
    "depth": 0.26,
    "anim": {
     "type": "wave",
     "a": 1,
     "t": 1.8617228133603931
    },
    "src": "assets/scenes/war_field/banner446.png"
   },
   {
    "id": "banner470",
    "x": 471,
    "y": 150,
    "w": 9,
    "h": 28,
    "depth": 0.26,
    "anim": {
     "type": "wave",
     "a": 1,
     "t": 1.53338020183146
    },
    "src": "assets/scenes/war_field/banner470.png"
   },
   {
    "id": "nishiki",
    "x": 65,
    "y": 148,
    "w": 16,
    "h": 11,
    "depth": 0.26,
    "anim": {
     "type": "wave",
     "a": 1,
     "t": 1.8
    },
    "src": "assets/scenes/war_field/nishiki.png"
   },
   {
    "id": "front",
    "x": 2,
    "y": 240,
    "w": 475,
    "h": 30,
    "depth": 0.8,
    "anim": {
     "type": "sway",
     "a": 1.2,
     "t": 3.6
    },
    "src": "assets/scenes/war_field/front.png"
   }
  ]
 },
 "war_guns": {
  "flat": "assets/scenes/war_guns/flat.png",
  "vignette": [
   0.45,
   "20,4,6"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/war_guns/sky.png"
   },
   {
    "id": "smoke_sky",
    "x": 0,
    "y": 39,
    "w": 480,
    "h": 66,
    "depth": 0.04,
    "anim": {
     "type": "drift",
     "t": 180
    },
    "src": "assets/scenes/war_guns/smoke_sky.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 172,
    "w": 480,
    "h": 98,
    "depth": 0.08,
    "anim": null,
    "src": "assets/scenes/war_guns/far.png"
   },
   {
    "id": "smoke",
    "x": 291,
    "y": 56,
    "w": 107,
    "h": 134,
    "depth": 0.1,
    "anim": null,
    "src": "assets/scenes/war_guns/smoke.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 190,
    "w": 480,
    "h": 80,
    "depth": 0.3,
    "anim": null,
    "src": "assets/scenes/war_guns/land.png"
   },
   {
    "id": "gun_far",
    "x": 278,
    "y": 188,
    "w": 170,
    "h": 38,
    "depth": 0.35,
    "anim": null,
    "src": "assets/scenes/war_guns/gun_far.png"
   },
   {
    "id": "gun_near",
    "x": 16,
    "y": 192,
    "w": 269,
    "h": 74,
    "depth": 0.55,
    "anim": null,
    "src": "assets/scenes/war_guns/gun_near.png"
   },
   {
    "id": "bags",
    "x": 0,
    "y": 255,
    "w": 480,
    "h": 15,
    "depth": 0.8,
    "anim": null,
    "src": "assets/scenes/war_guns/bags.png"
   }
  ]
 },
 "war_horizon": {
  "flat": "assets/scenes/war_horizon/flat.png",
  "vignette": [
   0.45,
   "20,4,6"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/war_horizon/sky.png"
   },
   {
    "id": "smoke_sky",
    "x": 0,
    "y": 23,
    "w": 480,
    "h": 89,
    "depth": 0.04,
    "anim": {
     "type": "drift",
     "t": 260
    },
    "src": "assets/scenes/war_horizon/smoke_sky.png"
   },
   {
    "id": "balloon",
    "x": 89,
    "y": 63,
    "w": 33,
    "h": 122,
    "depth": 0.08,
    "anim": {
     "type": "bob",
     "a": 1.5,
     "t": 7
    },
    "src": "assets/scenes/war_horizon/balloon.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 154,
    "w": 480,
    "h": 116,
    "depth": 0.06,
    "anim": null,
    "src": "assets/scenes/war_horizon/far.png"
   },
   {
    "id": "town",
    "x": 2,
    "y": 101,
    "w": 478,
    "h": 90,
    "depth": 0.1,
    "anim": null,
    "src": "assets/scenes/war_horizon/town.png"
   },
   {
    "id": "smoke",
    "x": 91,
    "y": 0,
    "w": 330,
    "h": 186,
    "depth": 0.12,
    "anim": null,
    "src": "assets/scenes/war_horizon/smoke.png"
   },
   {
    "id": "land",
    "x": 0,
    "y": 152,
    "w": 480,
    "h": 118,
    "depth": 0.3,
    "anim": null,
    "src": "assets/scenes/war_horizon/land.png"
   },
   {
    "id": "grass",
    "x": 0,
    "y": 246,
    "w": 480,
    "h": 24,
    "depth": 0.7,
    "anim": {
     "type": "sway",
     "a": 1.6,
     "t": 3.4
    },
    "src": "assets/scenes/war_horizon/grass.png"
   }
  ]
 },
 "yuki_house": {
  "flat": "assets/scenes/yuki_house/flat.png",
  "vignette": [
   0.5,
   "10,14,20"
  ],
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/scenes/yuki_house/sky.png"
   },
   {
    "id": "maple",
    "x": 131,
    "y": 80,
    "w": 91,
    "h": 110,
    "depth": 0.2,
    "anim": {
     "type": "sway",
     "a": 1,
     "t": 6
    },
    "src": "assets/scenes/yuki_house/maple.png"
   },
   {
    "id": "room",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0.5,
    "anim": null,
    "src": "assets/scenes/yuki_house/room.png"
   }
  ]
 }
};
