/* Generated by tools/paint-walks.js: the layers of each walking area. */
window.VN_WALKSCENERY = {
 "aviary": {
  "w": 960,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/aviary/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 34,
    "w": 960,
    "h": 48,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 200
    },
    "src": "assets/walks/aviary/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 129,
    "w": 594,
    "h": 141,
    "depth": 0.15,
    "anim": null,
    "src": "assets/walks/aviary/far.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 147,
    "w": 743,
    "h": 49,
    "depth": 0.45,
    "anim": null,
    "src": "assets/walks/aviary/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 64,
    "w": 960,
    "h": 148,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/aviary/ground.png"
   },
   {
    "id": "front",
    "x": 4,
    "y": 232,
    "w": 955,
    "h": 38,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 3,
     "t": 4
    },
    "src": "assets/walks/aviary/front.png"
   }
  ]
 },
 "camp": {
  "w": 1920,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/camp/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 2,
    "w": 1920,
    "h": 112,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 420
    },
    "src": "assets/walks/camp/clouds.png"
   },
   {
    "id": "paris",
    "x": 0,
    "y": 90,
    "w": 664,
    "h": 78,
    "depth": 0.08,
    "anim": null,
    "src": "assets/walks/camp/paris.png"
   },
   {
    "id": "giants",
    "x": 41,
    "y": 32,
    "w": 560,
    "h": 139,
    "depth": 0.1,
    "anim": null,
    "src": "assets/walks/camp/giants.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 95,
    "w": 733,
    "h": 109,
    "depth": 0.12,
    "anim": null,
    "src": "assets/walks/camp/far.png"
   },
   {
    "id": "rail",
    "x": 0,
    "y": 131,
    "w": 816,
    "h": 77,
    "depth": 0.2,
    "anim": null,
    "src": "assets/walks/camp/rail.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 143,
    "w": 1095,
    "h": 53,
    "depth": 0.38,
    "anim": null,
    "src": "assets/walks/camp/mid.png"
   },
   {
    "id": "harbour",
    "x": 640,
    "y": 91,
    "w": 466,
    "h": 105,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/camp/harbour.png"
   },
   {
    "id": "ship",
    "x": 647,
    "y": 6,
    "w": 337,
    "h": 180,
    "depth": 1,
    "anim": {
     "type": "bob",
     "a": 0.6,
     "t": 5.5
    },
    "src": "assets/walks/camp/ship.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 57,
    "w": 1920,
    "h": 155,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/camp/ground.png"
   },
   {
    "id": "front",
    "x": 2,
    "y": 234,
    "w": 1903,
    "h": 36,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 3,
     "t": 3.4
    },
    "src": "assets/walks/camp/front.png"
   }
  ]
 },
 "cemetery": {
  "w": 960,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/cemetery/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 41,
    "w": 960,
    "h": 62,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 260
    },
    "src": "assets/walks/cemetery/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 119,
    "w": 587,
    "h": 151,
    "depth": 0.14,
    "anim": null,
    "src": "assets/walks/cemetery/far.png"
   },
   {
    "id": "mid",
    "x": 14,
    "y": 128,
    "w": 720,
    "h": 68,
    "depth": 0.45,
    "anim": null,
    "src": "assets/walks/cemetery/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 75,
    "w": 960,
    "h": 137,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/cemetery/ground.png"
   },
   {
    "id": "front",
    "x": 8,
    "y": 234,
    "w": 948,
    "h": 36,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 3,
     "t": 3.6
    },
    "src": "assets/walks/cemetery/front.png"
   }
  ]
 },
 "crossing": {
  "w": 1440,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/crossing/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 22,
    "w": 1440,
    "h": 83,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 90
    },
    "src": "assets/walks/crossing/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 0,
    "w": 647,
    "h": 270,
    "depth": 0.1,
    "anim": null,
    "src": "assets/walks/crossing/far.png"
   },
   {
    "id": "field",
    "x": 0,
    "y": 146,
    "w": 760,
    "h": 124,
    "depth": 0.25,
    "anim": null,
    "src": "assets/walks/crossing/field.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 140,
    "w": 960,
    "h": 69,
    "depth": 0.45,
    "anim": null,
    "src": "assets/walks/crossing/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 147,
    "w": 1440,
    "h": 65,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/crossing/ground.png"
   },
   {
    "id": "front",
    "x": 14,
    "y": 232,
    "w": 1415,
    "h": 38,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 2,
     "t": 3.6
    },
    "src": "assets/walks/crossing/front.png"
   }
  ]
 },
 "lavilledieu": {
  "w": 1920,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/lavilledieu/sky.png"
   },
   {
    "id": "clouds_high",
    "x": 0,
    "y": 6,
    "w": 1920,
    "h": 51,
    "depth": 0.02,
    "anim": {
     "type": "drift",
     "t": 700
    },
    "src": "assets/walks/lavilledieu/clouds_high.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 19,
    "w": 1920,
    "h": 71,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 420
    },
    "src": "assets/walks/lavilledieu/clouds.png"
   },
   {
    "id": "peaks",
    "x": 0,
    "y": 38,
    "w": 640,
    "h": 140,
    "depth": 0.03,
    "anim": null,
    "src": "assets/walks/lavilledieu/peaks.png"
   },
   {
    "id": "range",
    "x": 0,
    "y": 76,
    "w": 711,
    "h": 114,
    "depth": 0.07,
    "anim": null,
    "src": "assets/walks/lavilledieu/range.png"
   },
   {
    "id": "hills",
    "x": 0,
    "y": 118,
    "w": 707,
    "h": 82,
    "depth": 0.13,
    "anim": null,
    "src": "assets/walks/lavilledieu/hills.png"
   },
   {
    "id": "hill",
    "x": 250,
    "y": 7,
    "w": 593,
    "h": 197,
    "depth": 0.22,
    "anim": null,
    "src": "assets/walks/lavilledieu/hill.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 49,
    "w": 1254,
    "h": 148,
    "depth": 0.5,
    "anim": null,
    "src": "assets/walks/lavilledieu/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 31,
    "w": 1920,
    "h": 181,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/lavilledieu/ground.png"
   },
   {
    "id": "front",
    "x": 49,
    "y": 233,
    "w": 1815,
    "h": 37,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 2.4,
     "t": 3.8
    },
    "src": "assets/walks/lavilledieu/front.png"
   }
  ]
 },
 "ruins": {
  "w": 1440,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/ruins/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 26,
    "w": 1440,
    "h": 78,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 160
    },
    "src": "assets/walks/ruins/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 139,
    "w": 654,
    "h": 131,
    "depth": 0.14,
    "anim": null,
    "src": "assets/walks/ruins/far.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 125,
    "w": 919,
    "h": 71,
    "depth": 0.45,
    "anim": null,
    "src": "assets/walks/ruins/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 115,
    "w": 1440,
    "h": 109,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/ruins/ground.png"
   },
   {
    "id": "front",
    "x": 25,
    "y": 233,
    "w": 1392,
    "h": 37,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 2,
     "t": 4
    },
    "src": "assets/walks/ruins/front.png"
   }
  ]
 },
 "steppe": {
  "w": 2400,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/steppe/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 29,
    "w": 2400,
    "h": 69,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 260
    },
    "src": "assets/walks/steppe/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 128,
    "w": 750,
    "h": 142,
    "depth": 0.12,
    "anim": null,
    "src": "assets/walks/steppe/far.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 126,
    "w": 1288,
    "h": 78,
    "depth": 0.4,
    "anim": null,
    "src": "assets/walks/steppe/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 154,
    "w": 2400,
    "h": 66,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/steppe/ground.png"
   },
   {
    "id": "front",
    "x": 2,
    "y": 234,
    "w": 2395,
    "h": 36,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 4,
     "t": 3
    },
    "src": "assets/walks/steppe/front.png"
   }
  ]
 },
 "village": {
  "w": 1920,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/village/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 13,
    "w": 1920,
    "h": 75,
    "depth": 0.04,
    "anim": {
     "type": "drift",
     "t": 360
    },
    "src": "assets/walks/village/clouds.png"
   },
   {
    "id": "peaks",
    "x": 0,
    "y": 41,
    "w": 563,
    "h": 229,
    "depth": 0.03,
    "anim": null,
    "src": "assets/walks/village/peaks.png"
   },
   {
    "id": "castle",
    "x": 0,
    "y": 31,
    "w": 645,
    "h": 196,
    "depth": 0.08,
    "anim": null,
    "src": "assets/walks/village/castle.png"
   },
   {
    "id": "uptown",
    "x": 0,
    "y": 50,
    "w": 846,
    "h": 155,
    "depth": 0.2,
    "anim": null,
    "src": "assets/walks/village/uptown.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 38,
    "w": 1199,
    "h": 158,
    "depth": 0.45,
    "anim": null,
    "src": "assets/walks/village/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 107,
    "w": 1920,
    "h": 127,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/village/ground.png"
   },
   {
    "id": "front",
    "x": 15,
    "y": 232,
    "w": 1894,
    "h": 38,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 3,
     "t": 3.8
    },
    "src": "assets/walks/village/front.png"
   }
  ]
 }
};
