/* Generated by tools/paint-walks.js: the layers of each walking area. */
window.VN_WALKSCENERY = {
 "aviary": {
  "w": 960,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/aviary/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 34,
    "w": 960,
    "h": 48,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 200
    },
    "src": "assets/walks/aviary/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 129,
    "w": 594,
    "h": 141,
    "depth": 0.15,
    "anim": null,
    "src": "assets/walks/aviary/far.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 147,
    "w": 743,
    "h": 49,
    "depth": 0.45,
    "anim": null,
    "src": "assets/walks/aviary/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 64,
    "w": 960,
    "h": 148,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/aviary/ground.png"
   },
   {
    "id": "front",
    "x": 4,
    "y": 232,
    "w": 955,
    "h": 38,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 3,
     "t": 4
    },
    "src": "assets/walks/aviary/front.png"
   }
  ]
 },
 "camp": {
  "w": 1440,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/camp/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 33,
    "w": 1440,
    "h": 49,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 300
    },
    "src": "assets/walks/camp/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 149,
    "w": 668,
    "h": 121,
    "depth": 0.15,
    "anim": null,
    "src": "assets/walks/camp/far.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 150,
    "w": 952,
    "h": 52,
    "depth": 0.45,
    "anim": null,
    "src": "assets/walks/camp/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 144,
    "w": 1440,
    "h": 68,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/camp/ground.png"
   },
   {
    "id": "front",
    "x": 45,
    "y": 236,
    "w": 1395,
    "h": 34,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 3,
     "t": 3.4
    },
    "src": "assets/walks/camp/front.png"
   }
  ]
 },
 "cemetery": {
  "w": 960,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/cemetery/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 41,
    "w": 960,
    "h": 62,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 260
    },
    "src": "assets/walks/cemetery/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 119,
    "w": 587,
    "h": 151,
    "depth": 0.14,
    "anim": null,
    "src": "assets/walks/cemetery/far.png"
   },
   {
    "id": "mid",
    "x": 14,
    "y": 128,
    "w": 720,
    "h": 68,
    "depth": 0.45,
    "anim": null,
    "src": "assets/walks/cemetery/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 75,
    "w": 960,
    "h": 137,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/cemetery/ground.png"
   },
   {
    "id": "front",
    "x": 8,
    "y": 234,
    "w": 948,
    "h": 36,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 3,
     "t": 3.6
    },
    "src": "assets/walks/cemetery/front.png"
   }
  ]
 },
 "ruins": {
  "w": 1440,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/ruins/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 26,
    "w": 1440,
    "h": 78,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 160
    },
    "src": "assets/walks/ruins/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 139,
    "w": 654,
    "h": 131,
    "depth": 0.14,
    "anim": null,
    "src": "assets/walks/ruins/far.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 125,
    "w": 919,
    "h": 71,
    "depth": 0.45,
    "anim": null,
    "src": "assets/walks/ruins/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 115,
    "w": 1440,
    "h": 109,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/ruins/ground.png"
   },
   {
    "id": "front",
    "x": 25,
    "y": 233,
    "w": 1392,
    "h": 37,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 2,
     "t": 4
    },
    "src": "assets/walks/ruins/front.png"
   }
  ]
 },
 "steppe": {
  "w": 2400,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/steppe/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 29,
    "w": 2400,
    "h": 69,
    "depth": 0.05,
    "anim": {
     "type": "drift",
     "t": 260
    },
    "src": "assets/walks/steppe/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 128,
    "w": 750,
    "h": 142,
    "depth": 0.12,
    "anim": null,
    "src": "assets/walks/steppe/far.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 126,
    "w": 1288,
    "h": 78,
    "depth": 0.4,
    "anim": null,
    "src": "assets/walks/steppe/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 154,
    "w": 2400,
    "h": 66,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/steppe/ground.png"
   },
   {
    "id": "front",
    "x": 2,
    "y": 234,
    "w": 2395,
    "h": 36,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 4,
     "t": 3
    },
    "src": "assets/walks/steppe/front.png"
   }
  ]
 },
 "village": {
  "w": 1440,
  "h": 270,
  "layers": [
   {
    "id": "sky",
    "x": 0,
    "y": 0,
    "w": 480,
    "h": 270,
    "depth": 0,
    "anim": null,
    "src": "assets/walks/village/sky.png"
   },
   {
    "id": "clouds",
    "x": 0,
    "y": 48,
    "w": 1440,
    "h": 67,
    "depth": 0.04,
    "anim": {
     "type": "drift",
     "t": 320
    },
    "src": "assets/walks/village/clouds.png"
   },
   {
    "id": "far",
    "x": 0,
    "y": 121,
    "w": 659,
    "h": 149,
    "depth": 0.14,
    "anim": null,
    "src": "assets/walks/village/far.png"
   },
   {
    "id": "mid",
    "x": 0,
    "y": 140,
    "w": 943,
    "h": 57,
    "depth": 0.45,
    "anim": null,
    "src": "assets/walks/village/mid.png"
   },
   {
    "id": "ground",
    "x": 0,
    "y": 123,
    "w": 1440,
    "h": 89,
    "depth": 1,
    "anim": null,
    "src": "assets/walks/village/ground.png"
   },
   {
    "id": "front",
    "x": 0,
    "y": 233,
    "w": 1439,
    "h": 37,
    "depth": 1.3,
    "anim": {
     "type": "sway",
     "a": 3,
     "t": 3.8
    },
    "src": "assets/walks/village/front.png"
   }
  ]
 }
};
